/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as AccountingIndexRouteImport } from './routes/accounting.index'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'
import { Route as ProductsCategoryRouteImport } from './routes/products.$category'
import { Route as AccountingSuppliersRouteImport } from './routes/accounting.suppliers'
import { Route as AccountingQuotationsRouteImport } from './routes/accounting.quotations'
import { Route as AccountingCustomersRouteImport } from './routes/accounting.customers'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const AccountingIndexRoute = AccountingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountingRoute,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ProductsRoute,
} as any)
const AccountingSuppliersRoute = AccountingSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingQuotationsRoute = AccountingQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingCustomersRoute = AccountingCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AccountingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/admin': typeof AdminRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/accounting/customers': typeof AccountingCustomersRoute
  '/accounting/quotations': typeof AccountingQuotationsRoute
  '/accounting/suppliers': typeof AccountingSuppliersRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/services/$service': typeof ServicesServiceRoute
  '/accounting/': typeof AccountingIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/quote': typeof QuoteRoute
  '/accounting/customers': typeof AccountingCustomersRoute
  '/accounting/quotations': typeof AccountingQuotationsRoute
  '/accounting/suppliers': typeof AccountingSuppliersRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/services/$service': typeof ServicesServiceRoute
  '/accounting': typeof AccountingIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/admin': typeof AdminRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/accounting/customers': typeof AccountingCustomersRoute
  '/accounting/quotations': typeof AccountingQuotationsRoute
  '/accounting/suppliers': typeof AccountingSuppliersRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/services/$service': typeof ServicesServiceRoute
  '/accounting/': typeof AccountingIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/admin'
    | '/products'
    | '/quote'
    | '/services'
    | '/accounting/customers'
    | '/accounting/quotations'
    | '/accounting/suppliers'
    | '/products/$category'
    | '/services/$service'
    | '/accounting/'
    | '/products/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/quote'
    | '/accounting/customers'
    | '/accounting/quotations'
    | '/accounting/suppliers'
    | '/products/$category'
    | '/services/$service'
    | '/accounting'
    | '/products'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/admin'
    | '/products'
    | '/quote'
    | '/services'
    | '/accounting/customers'
    | '/accounting/quotations'
    | '/accounting/suppliers'
    | '/products/$category'
    | '/services/$service'
    | '/accounting/'
    | '/products/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRouteWithChildren
  AdminRoute: typeof AdminRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/accounting/': {
      id: '/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AccountingIndexRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/accounting/suppliers': {
      id: '/accounting/suppliers'
      path: '/suppliers'
      fullPath: '/accounting/suppliers'
      preLoaderRoute: typeof AccountingSuppliersRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/quotations': {
      id: '/accounting/quotations'
      path: '/quotations'
      fullPath: '/accounting/quotations'
      preLoaderRoute: typeof AccountingQuotationsRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/customers': {
      id: '/accounting/customers'
      path: '/customers'
      fullPath: '/accounting/customers'
      preLoaderRoute: typeof AccountingCustomersRouteImport
      parentRoute: typeof AccountingRoute
    }
  }
}

interface AccountingRouteChildren {
  AccountingCustomersRoute: typeof AccountingCustomersRoute
  AccountingQuotationsRoute: typeof AccountingQuotationsRoute
  AccountingSuppliersRoute: typeof AccountingSuppliersRoute
  AccountingIndexRoute: typeof AccountingIndexRoute
}

const AccountingRouteChildren: AccountingRouteChildren = {
  AccountingCustomersRoute: AccountingCustomersRoute,
  AccountingQuotationsRoute: AccountingQuotationsRoute,
  AccountingSuppliersRoute: AccountingSuppliersRoute,
  AccountingIndexRoute: AccountingIndexRoute,
}

const AccountingRouteWithChildren = AccountingRoute._addFileChildren(
  AccountingRouteChildren,
)

interface ProductsRouteChildren {
  ProductsCategoryRoute: typeof ProductsCategoryRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCategoryRoute: ProductsCategoryRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesServiceRoute: typeof ServicesServiceRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceRoute: ServicesServiceRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRouteWithChildren,
  AdminRoute: AdminRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
